### ISSUE TITLE
s3_prefix Unused

### ISSUE THREAD

**Issue by a-nldisr** [dcos/dcos-ansible#118]
Hi, I was looking for the S3 state bucket for the exhibitor setup. In this search I found the s3_prefix variable declared in the defaults for the bootstrap node. It however seems to be unused. 

Could you tell me if this is intentional and how the s3 state bucket for DCOS exhibitor is used?

**Comment by a-nldisr** [comment]
Found how to use the s3 bucket with exhibitor, all that remains is that `s3_prefix` is an unused var.

**Comment by fatz** [comment]
ok I see what you mean. You're refering to that bootstrap role defaults file. Please ignore that.

DC/OS related options must be set in `dcos.config` (https://github.com/dcos/dcos-ansible#global-vars) like this:

```yaml
dcos:
  config:
    s3_prefix: foobar
````

in `dcos.config` you're able to set [DC/OS parameters](https://docs.d2iq.com/mesosphere/dcos/1.13/installing/production/advanced-configuration/configuration-reference/)
