### ISSUE TITLE
dcos-ansible does not wait for machines to start

### ISSUE THREAD

**Issue by bernadinm** [dcos/dcos-ansible#28]
dcos-ansible fails often for nodes that are added dynamically from the dcos-terraform environment. As per the logs, you can see that ansible attempts to gather facts from nodes that does not yet exist. Then it attempts the connection check.

https://gist.github.com/bernadinm/00fd4168b66339ddab79b1fad35a10ae

**Comment by bernadinm** [comment]
PR https://github.com/dcos/dcos-ansible/pull/15 fixes this

**Comment by sebbrandt87** [comment]
merged 🎉
