### ISSUE TITLE
Failed - Installation: Run DC/OS master installation

### ISSUE THREAD

**Issue by davorceman** [dcos/dcos-ansible#58]
Hello,
I'm trying to install DC/OS locally on my PC for learning purposes.
I created 4 CentOS 7 machines in Hyper-V, 

I'm getting this error, and I have no idea how to troubleshoot. Can someone direct me?

`TASK [DCOS.master : Installation: Run DC/OS master installation] **********************************************************************************************************************************************
fatal: [192.168.0.101]: FAILED! => {"changed": true, "cmd": "set -o pipefail; bash /tmp/dcos/1.13.0/dcos_install.sh master | systemd-cat -t dcos-install", "delta": "0:00:00.594769", "end": "2019-08-20 20:03:01.065196", "msg": "non-zero return code", "rc": 1, "start": "2019-08-20 20:03:00.470427", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}

`

`PLAY RECAP ****************************************************************************************************************************************************************************************************
*
192.168.0.100              : ok=36   changed=20   unreachable=0    failed=0    skipped=6    rescued=0    ignored=0
192.168.0.101              : ok=22   changed=12   unreachable=0    failed=1    skipped=2    rescued=0    ignored=0
192.168.0.102              : ok=15   changed=8    unreachable=0    failed=0    skipped=2    rescued=0    ignored=0
192.168.0.103              : ok=15   changed=8    unreachable=0    failed=0    skipped=2    rescued=0    ignored=0
`

This is from master node messages log

> Aug 20 20:25:09 dcos-master dcos-install: Starting DC/OS Install Process
Aug 20 20:25:09 dcos-master dcos-install: Running preflight checks
Aug 20 20:25:09 dcos-master dcos-install: Checking if DC/OS is already installed: PASS (Not installed)
Aug 20 20:25:09 dcos-master dcos-install: PASS Is SELinux in disabled mode, permissive mode or in enforcing mode with the targeted policy loaded?
Aug 20 20:25:09 dcos-master dcos-install: Checking if docker is installed and in PATH: PASS
Aug 20 20:25:09 dcos-master dcos-install: Checking if Docker is running: PASS
Aug 20 20:25:09 dcos-master dcos-install: Checking if docker is installed and in PATH: PASS
Aug 20 20:25:09 dcos-master dcos-install: Checking docker version requirement (>= 1.6): FAIL (0.18.0)
Aug 20 20:25:09 dcos-master dcos-install: Checking if curl is installed and in PATH: PASS
Aug 20 20:25:09 dcos-master dcos-install: Checking if bash is installed and in PATH: PASS
Aug 20 20:25:09 dcos-master dcos-install: Checking if ping is installed and in PATH: PASS
Aug 20 20:25:09 dcos-master dcos-install: Checking if tar is installed and in PATH: PASS
Aug 20 20:25:09 dcos-master dcos-install: Checking if xz is installed and in PATH: PASS
Aug 20 20:25:09 dcos-master dcos-install: Checking if unzip is installed and in PATH: PASS
Aug 20 20:25:09 dcos-master dcos-install: Checking if ipset is installed and in PATH: PASS
Aug 20 20:25:09 dcos-master dcos-install: Checking if systemd-notify is installed and in PATH: PASS
Aug 20 20:25:09 dcos-master dcos-install: Checking if systemd is installed and in PATH: PASS
Aug 20 20:25:09 dcos-master dcos-install: Checking systemd version requirement (>= 200): PASS (219)
Aug 20 20:25:09 dcos-master dcos-install: Checking if group 'nogroup' exists: PASS
Aug 20 20:25:09 dcos-master dcos-install: Checking if port 53 (required by dcos-net) is in use: PASS
Aug 20 20:25:09 dcos-master dcos-install: Checking if port 80 (required by adminrouter) is in use: PASS
Aug 20 20:25:09 dcos-master dcos-install: Checking if port 443 (required by adminrouter) is in use: PASS
Aug 20 20:25:09 dcos-master dcos-install: Checking if port 1050 (required by dcos-diagnostics) is in use: PASS
Aug 20 20:25:09 dcos-master dcos-install: Checking if port 2181 (required by zookeeper) is in use: PASS
Aug 20 20:25:09 dcos-master dcos-install: Checking if port 5050 (required by mesos-master) is in use: PASS
Aug 20 20:25:09 dcos-master dcos-install: Checking if port 7070 (required by cosmos) is in use: PASS
Aug 20 20:25:09 dcos-master dcos-install: Checking if port 8080 (required by marathon) is in use: PASS
Aug 20 20:25:09 dcos-master dcos-install: Checking if port 8101 (required by dcos-oauth) is in use: PASS
Aug 20 20:25:09 dcos-master dcos-install: Checking if port 8123 (required by mesos-dns) is in use: PASS
Aug 20 20:25:09 dcos-master dcos-install: Checking if port 8181 (required by exhibitor) is in use: PASS
Aug 20 20:25:09 dcos-master dcos-install: Checking if port 9000 (required by metronome) is in use: PASS
Aug 20 20:25:09 dcos-master dcos-install: Checking if port 9942 (required by metronome) is in use: PASS
Aug 20 20:25:09 dcos-master dcos-install: Checking if port 9990 (required by cosmos) is in use: PASS
Aug 20 20:25:09 dcos-master dcos-install: Checking if port 15055 (required by dcos-history) is in use: PASS
Aug 20 20:25:09 dcos-master dcos-install: Checking if port 36771 (required by marathon) is in use: PASS
Aug 20 20:25:09 dcos-master dcos-install: Checking if port 41281 (required by zookeeper) is in use: PASS
Aug 20 20:25:09 dcos-master dcos-install: Checking if port 46839 (required by metronome) is in use: PASS
Aug 20 20:25:09 dcos-master dcos-install: Checking if port 61053 (required by mesos-dns) is in use: PASS
Aug 20 20:25:09 dcos-master dcos-install: Checking if port 61091 (required by telegraf) is in use: PASS
Aug 20 20:25:09 dcos-master dcos-install: Checking if port 62020 (required by fluent-bit) is in use: PASS
Aug 20 20:25:09 dcos-master dcos-install: Checking if port 62080 (required by dcos-net) is in use: PASS
Aug 20 20:25:09 dcos-master dcos-install: Checking if port 62501 (required by dcos-net) is in use: PASS
Aug 20 20:25:09 dcos-master dcos-install: Checking Docker is configured with a production storage driver: PASS (overlay2)
Aug 20 20:25:09 dcos-master dcos-install: Checking if kernel module raid1 is loaded: WARNING Kernel module raid1 is not loaded. DC/OS Storage Service (DSS) depends on it.
Aug 20 20:25:09 dcos-master dcos-install: Checking if kernel module dm_raid is loaded: WARNING Kernel module dm_raid is not loaded. DC/OS Storage Service (DSS) depends on it.
Aug 20 20:25:09 dcos-master dcos-install: Preflight checks failed. Exiting installation. Please consult product documentation

**Comment by davorceman** [comment]
I found that this is known issue
http://docs-staging.mesosphere.com/mesosphere/dcos/services/storage/1.0.0/release-notes/

> And I loaded these modules.
> Now playbook again failed on the same step but with different error
> TASK [DCOS.master : Installation: Run DC/OS master installation] **********************************************************************************************************************************************
> fatal: [192.168.0.101]: FAILED! => {"changed": true, "cmd": "set -o pipefail; bash /tmp/dcos/1.13.0/dcos_install.sh master | systemd-cat -t dcos-install", "delta": "0:00:00.674359", "end": "2019-08-20 22:07:43.695860", "msg": "non-zero return code", "rc": 1, "start": "2019-08-20 22:07:43.021501", "stderr": "WARNING: bridge-nf-call-iptables is disabled\nWARNING: bridge-nf-call-ip6tables is disabled", "stderr_lines": ["WARNING: bridge-nf-call-iptables is disabled", "WARNING: bridge-nf-call-ip6tables is disabled"], "stdout": "", "stdout_lines": []}


And I don't see in /var/log/messages any warning

> Aug 20 22:07:43 dcos-master dcos-install: Starting DC/OS Install Process
Aug 20 22:07:43 dcos-master dcos-install: Running preflight checks
Aug 20 22:07:43 dcos-master dcos-install: Checking if DC/OS is already installed: PASS (Not installed)
Aug 20 22:07:43 dcos-master dcos-install: PASS Is SELinux in disabled mode, permissive mode or in enforcing mode with the targeted policy loaded?
Aug 20 22:07:43 dcos-master dcos-install: Checking if docker is installed and in PATH: PASS
Aug 20 22:07:43 dcos-master dcos-install: Checking if Docker is running: PASS
Aug 20 22:07:43 dcos-master dcos-install: Checking if docker is installed and in PATH: PASS
Aug 20 22:07:43 dcos-master dcos-install: Checking docker version requirement (>= 1.6): FAIL (0.18.0)
Aug 20 22:07:43 dcos-master dcos-install: Checking if curl is installed and in PATH: PASS
Aug 20 22:07:43 dcos-master dcos-install: Checking if bash is installed and in PATH: PASS
Aug 20 22:07:43 dcos-master dcos-install: Checking if ping is installed and in PATH: PASS
Aug 20 22:07:43 dcos-master dcos-install: Checking if tar is installed and in PATH: PASS
Aug 20 22:07:43 dcos-master dcos-install: Checking if xz is installed and in PATH: PASS
Aug 20 22:07:43 dcos-master dcos-install: Checking if unzip is installed and in PATH: PASS
Aug 20 22:07:43 dcos-master dcos-install: Checking if ipset is installed and in PATH: PASS
Aug 20 22:07:43 dcos-master dcos-install: Checking if systemd-notify is installed and in PATH: PASS
Aug 20 22:07:43 dcos-master dcos-install: Checking if systemd is installed and in PATH: PASS
Aug 20 22:07:43 dcos-master dcos-install: Checking systemd version requirement (>= 200): PASS (219)
Aug 20 22:07:43 dcos-master dcos-install: Checking if group 'nogroup' exists: PASS
Aug 20 22:07:43 dcos-master dcos-install: Checking if port 53 (required by dcos-net) is in use: PASS
Aug 20 22:07:43 dcos-master dcos-install: Checking if port 80 (required by adminrouter) is in use: PASS
Aug 20 22:07:43 dcos-master dcos-install: Checking if port 443 (required by adminrouter) is in use: PASS
Aug 20 22:07:43 dcos-master dcos-install: Checking if port 1050 (required by dcos-diagnostics) is in use: PASS
Aug 20 22:07:43 dcos-master dcos-install: Checking if port 2181 (required by zookeeper) is in use: PASS
Aug 20 22:07:43 dcos-master dcos-install: Checking if port 5050 (required by mesos-master) is in use: PASS
Aug 20 22:07:43 dcos-master dcos-install: Checking if port 7070 (required by cosmos) is in use: PASS
Aug 20 22:07:43 dcos-master dcos-install: Checking if port 8080 (required by marathon) is in use: PASS
Aug 20 22:07:43 dcos-master dcos-install: Checking if port 8101 (required by dcos-oauth) is in use: PASS
Aug 20 22:07:43 dcos-master dcos-install: Checking if port 8123 (required by mesos-dns) is in use: PASS
Aug 20 22:07:43 dcos-master dcos-install: Checking if port 8181 (required by exhibitor) is in use: PASS
Aug 20 22:07:43 dcos-master dcos-install: Checking if port 9000 (required by metronome) is in use: PASS
Aug 20 22:07:43 dcos-master dcos-install: Checking if port 9942 (required by metronome) is in use: PASS
Aug 20 22:07:43 dcos-master dcos-install: Checking if port 9990 (required by cosmos) is in use: PASS
Aug 20 22:07:43 dcos-master dcos-install: Checking if port 15055 (required by dcos-history) is in use: PASS
Aug 20 22:07:43 dcos-master dcos-install: Checking if port 36771 (required by marathon) is in use: PASS
Aug 20 22:07:43 dcos-master dcos-install: Checking if port 41281 (required by zookeeper) is in use: PASS
Aug 20 22:07:43 dcos-master dcos-install: Checking if port 46839 (required by metronome) is in use: PASS
Aug 20 22:07:43 dcos-master dcos-install: Checking if port 61053 (required by mesos-dns) is in use: PASS
Aug 20 22:07:43 dcos-master dcos-install: Checking if port 61091 (required by telegraf) is in use: PASS
Aug 20 22:07:43 dcos-master dcos-install: Checking if port 62020 (required by fluent-bit) is in use: PASS
Aug 20 22:07:43 dcos-master dcos-install: Checking if port 62080 (required by dcos-net) is in use: PASS
Aug 20 22:07:43 dcos-master dcos-install: Checking if port 62501 (required by dcos-net) is in use: PASS
Aug 20 22:07:43 dcos-master dcos-install: Checking Docker is configured with a production storage driver: PASS (overlay2)
Aug 20 22:07:43 dcos-master dcos-install: Checking if kernel module raid1 is loaded: PASS
Aug 20 22:07:43 dcos-master dcos-install: Checking if kernel module dm_raid is loaded: PASS
Aug 20 22:07:43 dcos-master dcos-install: Preflight checks failed. Exiting installation. Please consult product documentation

**Comment by sebbrandt87** [comment]
here is the FAIL message:
```Aug 20 22:07:43 dcos-master dcos-install: Checking docker version requirement (>= 1.6): FAIL (0.18.0)```

Please make sure for now that you install a docker_version listed here https://docs.d2iq.com/mesosphere/dcos/version-policy/#centos-support-matrix-2

**Comment by davorceman** [comment]
@sebbrandt87 thx for answer.
I'm running fresh Centos 7 on all nodes.

```
[root@dcos-master` ~]# docker version
Client: Docker Engine - Community
 Version:           19.03.2
 API version:       1.40
 Go version:        go1.12.8
 Git commit:        6a30dfc
 Built:             Thu Aug 29 05:28:55 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.2
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.8
  Git commit:       6a30dfc
  Built:            Thu Aug 29 05:27:34 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```


I have installed proper version from Docker 19.03.2

**Comment by sebbrandt87** [comment]
please make sure to pull the latest dcos version available, as there was a fixed bug within the install process. @davorceman
