### ISSUE TITLE
Connection timeouts from bootstrap to agent nodes

### ISSUE THREAD

**Issue by kricklen** [dcos/dcos-ansible#65]
Hello,

when trying to setup a dcos cluster on aws with the terraform module, i get the following error since this afternoon:

...
module.dcos.module.dcos-install.module.dcos-install.null_resource.run_ansible_from_bootstrap_node_to_install_dcos: Creating...
  triggers.%:                                 "" => "14"
  triggers.ansible_additional_config:         "" => ""
  triggers.ansible_bundled_container:         "" => "mesosphere/dcos-ansible-bundle:latest"
  triggers.ansible_force_run:                 "" => ""
  triggers.bootstrap_instance:                "" => "172.16.5.178"
  triggers.bootstrap_ip:                      "" => "xxx.xxx.xxx.xxx"
  triggers.dcos_config_yml:                   "" => "# Auto-generated by Terraform Templates\nbootstrap_url: http://172.16.5.178:8080\ncluster_name: dcos-demo\nresolvers:\n  - 169.254.169.253\nmaster_discovery: static\nexhibitor_storage_backend: static\nmaster_external_loadbalancer: xxx.xxx.xxx.xxx.elb.amazonaws.com\nmaster_list:\n  - 172.16.5.67\n  - 172.16.28.136\n  - 172.16.40.55\nfault_domain_detect_contents: |\n  #!/bin/sh\n  set -o nounset -o errexit\n  METADATA=\"$(curl http://169.254.169.254/latest/dynamic/instance-identity/document 2>/dev/null)\"\n  REGION=$(echo $METADATA | grep -Po \"\\\"region\\\"\\s+:\\s+\\\"(.*?)\\\"\" | cut -f2 -d:)\n  ZONE=$(echo $METADATA | grep -Po \"\\\"availabilityZone\\\"\\s+:\\s+\\\"(.*?)\\\"\" | cut -f2 -d:)\n  echo \"{\\\"fault_domain\\\":{\\\"region\\\":{\\\"name\\\": $REGION},\\\"zone\\\":{\\\"name\\\": $ZONE}}}\"\nip_detect_contents: |\n  #!/bin/sh\n  # Example ip-detect script using an external authority\n  # Uses the AWS Metadata Service to get the node's internal\n  # ipv4 address\n  set -o nounset -o errexit\n  curl -fsSL http://169.254.169.254/latest/meta-data/local-ipv4\nip_detect_public_contents: |\n  #!/bin/sh\n  set -o nounset -o errexit\n  curl -fsSL http://whatismyip.akamai.com/\nip_detect_public_filename: genconf/ip-detect-public"
  triggers.dcos_download_url:                 "" => "https://downloads.dcos.io/dcos/stable/1.13.3/dcos_generate_config.sh"
  triggers.dcos_variant:                      "" => "open"
  triggers.dcos_version:                      "" => "1.13.3"
  triggers.depends_on:                        "" => ""
  triggers.master_instances:                  "" => "172.16.5.67,172.16.28.136,172.16.40.55"
  triggers.private_agents_instances:          "" => "172.16.9.156,172.16.28.201,172.16.47.69,172.16.7.182,172.16.16.80,172.16.39.176,172.16.12.169,172.16.26.67,172.16.35.200"
  triggers.public_agents_instances:           "" => "172.16.1.116"
  triggers.windows_private_agent_private_ips: "" => ""
module.dcos.module.dcos-install.module.dcos-install.null_resource.run_ansible_from_bootstrap_node_to_install_dcos: Provisioning with 'file'...
module.dcos.module.dcos-install.module.dcos-install.null_resource.run_ansible_from_bootstrap_node_to_install_dcos: Provisioning with 'remote-exec'...
module.dcos.module.dcos-install.module.dcos-install.null_resource.run_ansible_from_bootstrap_node_to_install_dcos (remote-exec): Connecting to remote host via SSH...
module.dcos.module.dcos-install.module.dcos-install.null_resource.run_ansible_from_bootstrap_node_to_install_dcos (remote-exec):   Host: xxx.xxx.xxx.xxx
module.dcos.module.dcos-install.module.dcos-install.null_resource.run_ansible_from_bootstrap_node_to_install_dcos (remote-exec):   User: centos
module.dcos.module.dcos-install.module.dcos-install.null_resource.run_ansible_from_bootstrap_node_to_install_dcos (remote-exec):   Password: false
module.dcos.module.dcos-install.module.dcos-install.null_resource.run_ansible_from_bootstrap_node_to_install_dcos (remote-exec):   Private key: false
module.dcos.module.dcos-install.module.dcos-install.null_resource.run_ansible_from_bootstrap_node_to_install_dcos (remote-exec):   SSH Agent: true
module.dcos.module.dcos-install.module.dcos-install.null_resource.run_ansible_from_bootstrap_node_to_install_dcos (remote-exec):   Checking Host Key: false
module.dcos.module.dcos-install.module.dcos-install.null_resource.run_ansible_from_bootstrap_node_to_install_dcos (remote-exec): Connected!
module.dcos.module.dcos-install.module.dcos-install.null_resource.run_ansible_from_bootstrap_node_to_install_dcos (remote-exec): + '[' -f /etc/os-release ']'
module.dcos.module.dcos-install.module.dcos-install.null_resource.run_ansible_from_bootstrap_node_to_install_dcos (remote-exec): + . /etc/os-release
module.dcos.module.dcos-install.module.dcos-install.null_resource.run_ansible_from_bootstrap_node_to_install_dcos (remote-exec): ++ NAME='CentOS Linux'
module.dcos.module.dcos-install.module.dcos-install.null_resource.run_ansible_from_bootstrap_node_to_install_dcos (remote-exec): ++ VERSION='7 (Core)'
module.dcos.module.dcos-install.module.dcos-install.null_resource.run_ansible_from_bootstrap_node_to_install_dcos (remote-exec): ++ ID=centos
module.dcos.module.dcos-install.module.dcos-install.null_resource.run_ansible_from_bootstrap_node_to_install_dcos (remote-exec): ++ ID_LIKE='rhel fedora'
module.dcos.module.dcos-install.module.dcos-install.null_resource.run_ansible_from_bootstrap_node_to_install_dcos (remote-exec): ++ VERSION_ID=7
module.dcos.module.dcos-install.module.dcos-install.null_resource.run_ansible_from_bootstrap_node_to_install_dcos (remote-exec): ++ PRETTY_NAME='CentOS Linux 7 (Core)'
module.dcos.module.dcos-install.module.dcos-install.null_resource.run_ansible_from_bootstrap_node_to_install_dcos (remote-exec): ++ ANSI_COLOR='0;31'
module.dcos.module.dcos-install.module.dcos-install.null_resource.run_ansible_from_bootstrap_node_to_install_dcos (remote-exec): ++ CPE_NAME=cpe:/o:centos:centos:7
module.dcos.module.dcos-install.module.dcos-install.null_resource.run_ansible_from_bootstrap_node_to_install_dcos (remote-exec): ++ HOME_URL=https://www.centos.org/
module.dcos.module.dcos-install.module.dcos-install.null_resource.run_ansible_from_bootstrap_node_to_install_dcos (remote-exec): ++ BUG_REPORT_URL=https://bugs.centos.org/
module.dcos.module.dcos-install.module.dcos-install.null_resource.run_ansible_from_bootstrap_node_to_install_dcos (remote-exec): ++ CENTOS_MANTISBT_PROJECT=CentOS-7
module.dcos.module.dcos-install.module.dcos-install.null_resource.run_ansible_from_bootstrap_node_to_install_dcos (remote-exec): ++ CENTOS_MANTISBT_PROJECT_VERSION=7
module.dcos.module.dcos-install.module.dcos-install.null_resource.run_ansible_from_bootstrap_node_to_install_dcos (remote-exec): ++ REDHAT_SUPPORT_PRODUCT=centos
module.dcos.module.dcos-install.module.dcos-install.null_resource.run_ansible_from_bootstrap_node_to_install_dcos (remote-exec): ++ REDHAT_SUPPORT_PRODUCT_VERSION=7
module.dcos.module.dcos-install.module.dcos-install.null_resource.run_ansible_from_bootstrap_node_to_install_dcos (remote-exec): + OS=centos-7
module.dcos.module.dcos-install.module.dcos-install.null_resource.run_ansible_from_bootstrap_node_to_install_dcos (remote-exec): ++ command -v docker
module.dcos.module.dcos-install.module.dcos-install.null_resource.run_ansible_from_bootstrap_node_to_install_dcos (remote-exec): + '[' -x /usr/bin/docker ']'
module.dcos.module.dcos-install.module.dcos-install.null_resource.run_ansible_from_bootstrap_node_to_install_dcos (remote-exec): + sudo docker info
module.dcos.module.dcos-install.module.dcos-install.null_resource.run_ansible_from_bootstrap_node_to_install_dcos (remote-exec): + echo 'docker is running'
module.dcos.module.dcos-install.module.dcos-install.null_resource.run_ansible_from_bootstrap_node_to_install_dcos (remote-exec): docker is running
module.dcos.module.dcos-install.module.dcos-install.null_resource.run_ansible_from_bootstrap_node_to_install_dcos: Provisioning with 'file'...
module.dcos.module.dcos-install.module.dcos-install.null_resource.run_ansible_from_bootstrap_node_to_install_dcos: Provisioning with 'file'...
module.dcos.module.dcos-install.module.dcos-install.null_resource.run_ansible_from_bootstrap_node_to_install_dcos: Provisioning with 'remote-exec'...
module.dcos.module.dcos-install.module.dcos-install.null_resource.run_ansible_from_bootstrap_node_to_install_dcos (remote-exec): Connecting to remote host via SSH...
module.dcos.module.dcos-install.module.dcos-install.null_resource.run_ansible_from_bootstrap_node_to_install_dcos (remote-exec):   Host: xxx.xxx.xxx.xxx
module.dcos.module.dcos-install.module.dcos-install.null_resource.run_ansible_from_bootstrap_node_to_install_dcos (remote-exec):   User: centos
module.dcos.module.dcos-install.module.dcos-install.null_resource.run_ansible_from_bootstrap_node_to_install_dcos (remote-exec):   Password: false
module.dcos.module.dcos-install.module.dcos-install.null_resource.run_ansible_from_bootstrap_node_to_install_dcos (remote-exec):   Private key: false
module.dcos.module.dcos-install.module.dcos-install.null_resource.run_ansible_from_bootstrap_node_to_install_dcos (remote-exec):   SSH Agent: true
module.dcos.module.dcos-install.module.dcos-install.null_resource.run_ansible_from_bootstrap_node_to_install_dcos (remote-exec):   Checking Host Key: false
module.dcos.module.dcos-install.module.dcos-install.null_resource.run_ansible_from_bootstrap_node_to_install_dcos (remote-exec): Connected!
module.dcos.module.dcos-install.module.dcos-install.null_resource.run_ansible_from_bootstrap_node_to_install_dcos (remote-exec): latest: Pulling from mesosphere/dcos-ansible-bundle
module.dcos.module.dcos-install.module.dcos-install.null_resource.run_ansible_from_bootstrap_node_to_install_dcos (remote-exec): Digest: sha256:c41d840adedcaa67daa180232c17a6741a7332bbb5eef6fa44238d042402c320
module.dcos.module.dcos-install.module.dcos-install.null_resource.run_ansible_from_bootstrap_node_to_install_dcos (remote-exec): Status: Image is up to date for mesosphere/dcos-ansible-bundle:latest
module.dcos.module.dcos-install.module.dcos-install.null_resource.run_ansible_from_bootstrap_node_to_install_dcos (remote-exec): docker.io/mesosphere/dcos-ansible-bundle:latest

module.dcos.module.dcos-install.module.dcos-install.null_resource.run_ansible_from_bootstrap_node_to_install_dcos (remote-exec): PLAY [Wait for instances to become reachable] **********************************

module.dcos.module.dcos-install.module.dcos-install.null_resource.run_ansible_from_bootstrap_node_to_install_dcos (remote-exec): TASK [Wait for instances to become reachable] **********************************
module.dcos.dcos-install.dcos-install.null_resource.run_ansible_from_bootstrap_node_to_install_dcos: Still creating... (10s elapsed)
module.dcos.dcos-install.dcos-install.null_resource.run_ansible_from_bootstrap_node_to_install_dcos: Still creating... (20s elapsed)
module.dcos.dcos-install.dcos-install.null_resource.run_ansible_from_bootstrap_node_to_install_dcos: Still creating... (30s elapsed)
module.dcos.dcos-install.dcos-install.null_resource.run_ansible_from_bootstrap_node_to_install_dcos: Still creating... (40s elapsed)
module.dcos.dcos-install.dcos-install.null_resource.run_ansible_from_bootstrap_node_to_install_dcos: Still creating... (50s elapsed)
module.dcos.dcos-install.dcos-install.null_resource.run_ansible_from_bootstrap_node_to_install_dcos: Still creating... (1m0s elapsed)
module.dcos.dcos-install.dcos-install.null_resource.run_ansible_from_bootstrap_node_to_install_dcos: Still creating... (1m10s elapsed)
module.dcos.dcos-install.dcos-install.null_resource.run_ansible_from_bootstrap_node_to_install_dcos: Still creating... (1m20s elapsed)
module.dcos.dcos-install.dcos-install.null_resource.run_ansible_from_bootstrap_node_to_install_dcos: Still creating... (1m30s elapsed)
module.dcos.dcos-install.dcos-install.null_resource.run_ansible_from_bootstrap_node_to_install_dcos: Still creating... (1m40s elapsed)
module.dcos.dcos-install.dcos-install.null_resource.run_ansible_from_bootstrap_node_to_install_dcos: Still creating... (1m50s elapsed)
module.dcos.dcos-install.dcos-install.null_resource.run_ansible_from_bootstrap_node_to_install_dcos: Still creating... (2m0s elapsed)
module.dcos.dcos-install.dcos-install.null_resource.run_ansible_from_bootstrap_node_to_install_dcos: Still creating... (2m10s elapsed)
module.dcos.module.dcos-install.module.dcos-install.null_resource.run_ansible_from_bootstrap_node_to_install_dcos (remote-exec): fatal: [172.16.5.67]: FAILED! => {"changed": false, "elapsed": 131, "msg": "timed out waiting for ping module test success: SSH Error: data could not be sent to remote host \"172.16.5.67\". Make sure this host can be reached over ssh"}
module.dcos.module.dcos-install.module.dcos-install.null_resource.run_ansible_from_bootstrap_node_to_install_dcos (remote-exec): fatal: [172.16.9.156]: FAILED! => {"changed": false, "elapsed": 130, "msg": "timed out waiting for ping module test success: SSH Error: data could not be sent to remote host \"172.16.9.156\". Make sure this host can be reached over ssh"}
...

I replaced the public info of the bootstrap host etc.

The same procedure was working this morning, so i guess some change to the ansible code in docker image is causing the issue.

**Comment by sebbrandt87** [comment]
true, we already reverted one commit. please make sure to pull the docker image `mesosphere/dcos-ansible-bundle:latest` again on the bootstrap node.
should be done with the terraform execution.

**Comment by kricklen** [comment]
Yes, works again, thanks :)
